name: doctorwho
services:
  db:
    image: mariadb:11.3.2
    container_name: doctorwho-db-dev
    environment:
      MYSQL_DATABASE: 'aa_doctorwho' 
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: '5Jtlt6!!mar'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - doctorwho_data:/var/lib/mysql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: doctorwho-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: always

  tomcat:
    image: tomcat:9.0.105-jdk21-temurin
    container_name: doctorwho-tomcat
    depends_on:
      - db
    ports:
      - "8083:8080"
    volumes:
      - ./target/doctorwho.war:/usr/local/tomcat/webapps/doctorwho.war
    command: ["catalina.sh", "run"]
    restart: always

volumes:
  doctorwho_data: